version: '3.3'

services:
  db:
    image: postgres:15
    container_name: project_postgres
    volumes:
      - ~/.pg/pg_data/project:/var/lib/postgresql/data
    env_file:
      - .env
  project:
    build:
      dockerfile: Dockerfile
      context: .
    image: project:latest
    container_name: project
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: 
      bash -c "python manage.py migrate  && gunicorn -b 0.0.0.0:8000 project.wsgi:application --log-level info"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: project_nginx
    image: project_nginx
    depends_on:
      - project
    ports:
      - "80:80"
